### ISSUE TITLE
[Feature] add debug/entrypoint/interactive flag(s)

### ISSUE THREAD

**Issue by sfuerte** [lavie/runlike#68]
Pretty similar to `runlike --no-name` which when I run it now, I'd get:
```
docker run --hostname=... --detach=true -t <image>:latest
```

As `runlike` is used mainly for duplicating a container during debugging (well, at least in my case and per my assumption), then it would be great to have `detach` replaced with the following:

```
docker run --hostname=... --entrypoint bash -i -t <image>:latest
```

I saw there is a PR https://github.com/lavie/runlike/pull/58 has been sitting for more than year (and which is outdated already) but it'd be great to implement something like that based on that branch.

**Comment by cweekly** [comment]
Yes, this, +1, upvote. Per the README, this is on maintainer's radar, my comment here is to support prioritizing this over other roadmap items. I'd guess the ROI here is significant for this prime use case.

**Comment by lavie** [comment]
I fail to see the connection between #58 and this to be honest. One is about `--entrypoint` and `--rm` and this suggestion is about replacing `detach` with `--it`...
Anyway, is it that hard to replace `-d` with `--it` when pasting the output into command line? Because `runlike`, up till now, did not modify existing flags on containers - that's kind of against the point. I get that sometimes you want to take a detached container and run it interactively, but all it takes in that case is to erase one param and add another. I'm not sure it warrants a CLI flag for `runlike` just for that. I mean, some other users might want a `runlike` CLI option to change the network from bridge to host, etc. you see what I mean?

Not currently convinced this is a worthwhile feature but happy to hear counterarguments.
