### ISSUE TITLE
Feature Request: Support for podman

### ISSUE THREAD

**Issue by ctml91** [lavie/runlike#71]
Would be nice to see this support podman. Most commands (if not all) are basically like aliases and work the same (e.g. podman inspect, etc)

```
Storing signatures
Error: statfs /var/run/docker.sock: no such file or directory
[root@fedora ~]# ls -lth /var/run/podman/podman.sock
srw-rw----. 1 root root 0 Apr 24 18:04 /var/run/podman/podman.so
```

**Comment by lavie** [comment]
Thanks, @ClavinJune .
I'm sorry for taking so long to respond to your PR. Currently the PR does not pass CI tests because `podman` is not installed as part of the CI. see https://github.com/lavie/runlike/blob/master/.github/workflows/ci.yaml

Would podman work even without a k8d cluster running? Otherwise it's going to be tricky to add testing for this. What are your thoughts?
